app:
  PEDESTAL_SERVER:
    server_url: "https://api.deepseek.com"
    api_key: "sk-e0d345b888b6445faef8c583b454141d"
celery:
  broker_url: "redis://172.16.0.4:6379/0"
  result_backend: "redis://172.16.0.4:6379/1"
