llama_server:
  url: "http://fauxpilot.wxl.com:32133/"
  timeout: 300

phind_server:
  url: "https://chatgpt.sangfor.com/utpilot/"
  timeout: 300

sdk:
  req_timeout:
    240
  req_times:
    10
  max_point:
    10

language:
  c++:
    suffix: [ ".c++", ".cc", ".cp", ".cpp", ".cxx", ".inl" ]
    frame: "gtest"
  c:
    suffix: [ ".c" ]
    frame: "gtest"
  go:
    suffix: [ ".go" ]
    frame: "gotest"
  python:
    suffix: [ ".python" ]
    frame: "pytest"

# 默认模型
use_model:
  PhindModel

# 单测结果文件命名间隔符，用于根据文件名切割获取对应数据：文件名，方法命名，用例号
ut_result_file_spc: "---"

models:
  Llama7BModel:
    regular: ""
    point_template: "Please help me analyze a piece of {language} code and give its unit test plan using {test_frame}.\n
                    The test plan includes many scenarios. List them to me beginning with ### and ending with ###. \n
                    The piece of {language} code is {code_context}."
    case_template: "Please help me generate a whole {language} test for a focal method in a focal class.\n
     I will provide the following information: 1. Required dependencies to include.\n
     2. The focal class information, including source code of the focal method.\n
     And I will give you a basic test plan to guide you to test better, the test plan is: {code_context}.\n
     I need you to create a whole unit test using {test_frame}.\n
     The test should include necessary includes for {test_frame}, compile without errors. No additional explanations required."
    token_length:
      input_length: 1500
      all_length: 3000
    stream: false
    max_workers: 1
  Llama34BModel:
    regular: ""
    point_template: "Please help me analyze a piece of {language} code and give its unit test plan using {test_frame}.\n
                    The test plan includes many scenarios. List them to me beginning with ### and ending with ###. \n
                    The piece of {language} code is {code_context}."
    case_template: "Please help me generate a whole {language} test for a focal method in a focal class.\n
     I will provide the following information: 1. Required dependencies to include.\n
     2. The focal class information, including source code of the focal method.\n
     And I will give you a basic test plan to guide you to test better, the test plan is: {code_context}.\n
     I need you to create a whole unit test using {test_frame}.\n
     The test should include necessary includes for {test_frame}, compile without errors. No additional explanations required."
    token_length:
      input_length: 1500
      all_length: 3000
    stream: false
    max_workers: 1
  PhindModel:
    regular: ""
    point_template: "Please help me analyze a piece of {language} code and give its unit test plan using {test_frame}.\n
                    The test plan includes many scenarios. List them to me beginning with ### and ending with ###. \n
                    The piece of {language} code is {code_context}."
    case_template: "Please help me generate a whole {language} test for a focal method in a focal class.\n
     I will provide the following information: 1. Required dependencies to include.\n
     2. The focal class information, including source code of the focal method.\n
     And I will give you a basic test plan to guide you to test better, the test plan is: {code_context}.\n
     I need you to create a whole unit test using {test_frame}.\n
     The test should include necessary includes for {test_frame}, compile without errors. No additional explanations required."
    token_length:
      input_length: 1000
      all_length: 2000
    stream: false
    max_workers: 2
  GPTModel:
    regular: ""
    point_template: "Please help me analyze a piece of {language} code and give its unit test plan using {test_frame}.\n
                    The test plan includes many scenarios. List them to me beginning with ### and ending with ###. \n
                    The piece of {language} code is {code_context}."
    case_template: "Please help me generate a whole {language} test for a focal method in a focal class.\n
     I will provide the following information: 1. Required dependencies to include.\n
     2. The focal class information, including source code of the focal method.\n
     And I will give you a basic test plan to guide you to test better, the test plan is: {code_context}.\n
     I need you to create a whole unit test using {test_frame}.\n
     The test should include necessary includes for {test_frame}, compile without errors. No additional explanations required."
    token_length:
      input_length: 1500
      all_length: 3000
    stream: false
    temperature: 0.3
    max_workers: 4
