#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    简单介绍

    :作者: 苏德利 16646
    :时间: 2023/3/3 15:20
    :修改者: 苏德利 16646
    :更新时间: 2023/3/3 15:20
"""
from common.constant import ActionsConstant, ConfigurationConstant
from template.advise import ADVISE_PROMPT
from template.add_comment import INITIAL_PROMPT as ADD_COMMENT_INITIAL_PROMPT
from template.add_debug_code import INITIAL_PROMPT as ADD_DEBUG_CODE_INITIAL_PROMPT
from template.add_stronger_code import INITIAL_PROMPT as ADD_STRONGER_CODE_INITIAL_PROMPT
from template.api_test_case import API_TEST_CASE_PROMPT, API_TEST_SINGLE_CASE_PROMPT, API_TEST_GEN_STEP_PROMPT, \
    API_TEST_CASE_MODIFY_PROMPT, API_TEST_CASE_REPEAT_VERIFIED_PROMPT, API_TEST_ODG_PROMPT, \
    API_TEST_POINT_DOC_INSPECTOR_PROMPT, API_TEST_PARAM_TYPE_ERROR_VERIFIED_PROMPT
from template.auto_review import INITIAL_PROMPT as AUTO_REVIEW_INITIAL_PROMPT
from template.explain_code import INITIAL_PROMPT as EXPLAIN_INITIAL_PROMPT
from template.find_bugs import INITIAL_PROMPT as FIND_BUGS_INITIAL_PROMPT
from template.generate_code import ASK_PROMPT as GENERATE_CODE_BY_ASK_INITIAL_PROMPT
from template.generate_code import FORM_PROMPT as GENERATE_CODE_BY_FORM_INITIAL_PROMPT
from template.generate_code import INITIAL_PROMPT as GENERATE_CODE_INITIAL_PROMPT
from template.generate_unit_test import INITIAL_PROMPT as ADD_TEST_INITIAL_PROMPT
from template.js2ts import INITIAL_PROMPT as JS2TS_INITIAL_PROMPT
from template.manual_review import INITIAL_PROMPT as MANUAL_REVIEW_INITIAL_PROMPT
from template.merge_code import MERGE_CODE_PROMPT
from template.improve_readability import INITIAL_PROMPT as OPTIMIZE_INITIAL_PROMPT
from template.pick_common_func import INITIAL_PROMPT as PICK_COMMON_FUNC_INITIAL_PROMPT
from template.scribe_dialogue import INITIAL_PROMPT_OPTIMIZED, INITIAL_GENERAL_PROMPT, INITIAL_TAG_PROMPT, \
    INITIAL_SELECT_PROMPT, INITIAL_REPLACE_PROMPT, INITIAL_PROMPT_COMPONENT
from template.simplify_code import INITIAL_PROMPT as SIMPLIFY_CODE_INITIAL_PROMPT
from template.continue_content import INITIAL_PROMPT as CONTINUE_CONTENT_INITIAL_PROMPT
from template.generate_api_test import INITIAL_API_TEST_POINT_PROMPT, INITIAL_API_TEST_SET_PROMPT
from template.ai_e2e_case import (
    E2E_MANUAL_CASE_CHECK_PROMPT,
    E2E_CASE_GEN_PROMPT,
    E2E_RAG_FILTER_PROMPT,
    E2E_STEP_INTENT_EXTRACT_PROMPT,
    E2E_IDENTIFY_RELATIONSHIPS_PROMPT
)

"""
prompt默认模板
"""
DEFAULT_TEMPLATE_MAP = {
    ActionsConstant.FIND_BUGS: FIND_BUGS_INITIAL_PROMPT,
    ActionsConstant.ADD_TEST: ADD_TEST_INITIAL_PROMPT,
    ActionsConstant.OPTIMIZE: OPTIMIZE_INITIAL_PROMPT,
    ActionsConstant.EXPLAIN: EXPLAIN_INITIAL_PROMPT,
    ActionsConstant.ADVISE: ADVISE_PROMPT,
    ActionsConstant.GENERATE_CODE: GENERATE_CODE_INITIAL_PROMPT,
    ActionsConstant.GENERATE_CODE_BY_FORM: GENERATE_CODE_BY_FORM_INITIAL_PROMPT,
    ActionsConstant.GENERATE_CODE_BY_ASK: GENERATE_CODE_BY_ASK_INITIAL_PROMPT,
    ActionsConstant.JS2TS: JS2TS_INITIAL_PROMPT,
    # ActionsConstant.REVIEW: MANUAL_REVIEW_INITIAL_PROMPT,
    ActionsConstant.ADD_DEBUG_CODE: ADD_DEBUG_CODE_INITIAL_PROMPT,
    ActionsConstant.ADD_STRONGER_CODE: ADD_STRONGER_CODE_INITIAL_PROMPT,
    ActionsConstant.ADD_COMMENT: ADD_COMMENT_INITIAL_PROMPT,
    ActionsConstant.PICK_COMMON_FUNC: PICK_COMMON_FUNC_INITIAL_PROMPT,
    ActionsConstant.SIMPLIFY_CODE: SIMPLIFY_CODE_INITIAL_PROMPT,
    # 生成api测试
    ActionsConstant.GENERATE_API_TEST_POINT: INITIAL_API_TEST_POINT_PROMPT,
    ActionsConstant.GENERATE_API_TEST_SET: INITIAL_API_TEST_SET_PROMPT,
    ActionsConstant.API_TEST_CASE: API_TEST_CASE_PROMPT,
    ActionsConstant.API_TEST_POINT_DOC_INSPECTOR: API_TEST_POINT_DOC_INSPECTOR_PROMPT,
    ActionsConstant.API_TEST_GEN_ODG: API_TEST_ODG_PROMPT,
    ActionsConstant.API_TEST_CASE_REPEAT_VERIFIED: API_TEST_CASE_REPEAT_VERIFIED_PROMPT,
    ActionsConstant.API_TEST_PARAM_TYPE_ERROR_VERIFIED: API_TEST_PARAM_TYPE_ERROR_VERIFIED_PROMPT,
    ActionsConstant.API_TEST_GEN_STEP: API_TEST_GEN_STEP_PROMPT,
    ActionsConstant.API_TEST_SINGLE_CASE: API_TEST_SINGLE_CASE_PROMPT,
    ActionsConstant.API_TEST_CASE_MODIFY: API_TEST_CASE_MODIFY_PROMPT,
    # 生成E2E自动化测试
    ActionsConstant.E2E_MANUAL_CASE_CHECK: E2E_MANUAL_CASE_CHECK_PROMPT,
    ActionsConstant.E2E_IDENTIFY_RELATIONSHIPS: E2E_IDENTIFY_RELATIONSHIPS_PROMPT,
    ActionsConstant.E2E_STEP_INTENT_EXTRACT: E2E_STEP_INTENT_EXTRACT_PROMPT,
    ActionsConstant.E2E_RAG_FILTER: E2E_RAG_FILTER_PROMPT,
    ActionsConstant.E2E_CASE_GEN: E2E_CASE_GEN_PROMPT,
    # 主动/自动review
    ConfigurationConstant.MANUAL_REVIEW_PROMPT: MANUAL_REVIEW_INITIAL_PROMPT,
    ConfigurationConstant.AUTO_REVIEW_PROMPT: AUTO_REVIEW_INITIAL_PROMPT,
    # 划词对话
    ConfigurationConstant.SCRIBE_ADD_TAG_PROMPT: INITIAL_TAG_PROMPT,
    ConfigurationConstant.SCRIBE_FILTER_DESC_PROMPT: INITIAL_SELECT_PROMPT,
    ConfigurationConstant.SCRIBE_GENERATE_CODE_PROMPT: INITIAL_PROMPT_OPTIMIZED,
    ConfigurationConstant.SCRIBE_FILTER_COMPONENT_API: INITIAL_PROMPT_COMPONENT,
    ConfigurationConstant.SCRIBE_GENERAL_PROMPT: INITIAL_GENERAL_PROMPT,
    ConfigurationConstant.SCRIBE_MERGE_CODE_PROMPT: MERGE_CODE_PROMPT,
    ConfigurationConstant.SCRIBE_REPLACE_PROMPT: INITIAL_REPLACE_PROMPT,
    # 续写内容
    ConfigurationConstant.CONTINUE_PROMPT: CONTINUE_CONTENT_INITIAL_PROMPT,
}
