apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-job
  namespace: shenma
spec:
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:20.0.5
        args: ["build"]
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: DB_ADDR
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          value: "password"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD 
          value: "admin"
        volumeMounts:
        - name: keycloak-configure
          mountPath: /opt/keycloak/conf/keycloak.conf
          subPath: keycloak.conf
        - name: keycloak-providers
          mountPath: /opt/keycloak/providers
      volumes:
      - name: keycloak-configure
        configMap:
          name: keycloak-configure
      - name: keycloak-providers
        persistentVolumeClaim:
          claimName: keycloak-providers
      restartPolicy: Never
