apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:3.9.1-debian
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 9180
        - containerPort: 9080
        - containerPort: 9443
        - containerPort: 9091
        - containerPort: 9092
        volumeMounts:
        - name: apisix-config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
      volumes:
      - name: apisix-config
        configMap:
          name: apisix-config
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-entry
  namespace: shenma
spec:
  type: NodePort
  ports:
  - name: admin
    port: 9180
    targetPort: 9180
    nodePort: 30180
  - name: http
    port: 9080
    targetPort: 9080
    nodePort: 30080
  - name: https
    port: 9443
    targetPort: 9443
    nodePort: 30443
  selector:
    app: apisix
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: shenma
spec:
  ports:
  - name: prometheus
    port: 9091
    targetPort: 9091
  - name: control
    port: 9092
    targetPort: 9092
  selector:
    app: apisix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: shenma
data:
  config.yaml: |
    apisix:
      node_listen: 9080              # APISIX listening port
      enable_ipv6: false
      enable_control: true
      control:
        ip: "0.0.0.0"
        port: 9092
    deployment:
      admin:
        allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
          - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.
        admin_key:
          - name: "admin"
            key: edd1c9f034335f136f87ad84b625c8f1
            role: admin                 # admin: manage all configuration data
          - name: "viewer"
            key: 4054f7cf07e344346cd3f287985e76a2
            role: viewer
      etcd:
        host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
          - "http://etcd:2379"          # multiple etcd address
        prefix: "/apisix"               # apisix configurations prefix
        timeout: 30                     # 30 seconds
    plugin_attr:
      prometheus:
        export_addr:
          ip: "0.0.0.0"
          port: 9091
    nginx_config:
      http_end_configuration_snippet: |
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
