apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-v2
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-v2
  template:
    metadata:
      labels:
        app: chatgpt-v2
    spec:
      containers:
      - name: chatgpt
        image: docker.sangfor.com/containerd/chatgpt/server:1.5.9
        imagePullPolicy: IfNotPresent
        # command: ["gunicorn", "app:app", "-w", "4", "-b", "0.0.0.0:5000"]
        ports:
        - containerPort: 5000
        - containerPort: 8765
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: CACHE_DB
          value: "chatgpt"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: SERVE_THREADS
          value: "200"
        - name: SERVE_CONNECTION_LIMIT
          value: "512"
        - name: PG_URL
          value: "postgres"
        - name: DB_NAME
          value: "chatgpt"
        - name: DATABASE_URI
          value: "postgresext+pool://keycloak:password@postgres/chatgpt"
        - name: ES_SERVER
          value: "http://quickstart-es-http:9200"
        - name: ES_PASSWORD
          value: "4c6y4g6Z09T2w33pYRNKE3LG"
        - name: DEVOPS_URL
          value: ""
        - name: GEVENT_SUPPORT
          value: "True"
        - name: NO_COLOR
          value: "1"
        - name: DEPLOYMENT_TYPE
          value: "all"
        volumeMounts:
        - name: logs-volume
          mountPath: /server/logs
        - name: supervisor-volume
          mountPath: /var/log/supervisor
        - name: server-volume
          mountPath: /server
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: chatgpt-logs
      - name: supervisor-volume
        persistentVolumeClaim:
          claimName: chatgpt-supervisor
      - name: server-volume
        persistentVolumeClaim:
          claimName: chatgpt-server
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt
  namespace: shenma
spec:
  ports:
  - name: entry
    port: 5000
    targetPort: 5000
  - name: other
    port: 8765
    targetPort: 8765
  selector:
    app: chatgpt-v2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatgpt-logs
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatgpt-supervisor
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatgpt-server
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


