apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: discovery.type
          value: "single-node"
        - name: bootstrap.memory_lock
          value: "true"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # 根据需要调整存储大小
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: shenma
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30200
    protocol: TCP
    name: api
  - port: 9300
    targetPort: 9300
    nodePort: 30300
    protocol: TCP
    name: inner
  selector:
    app: elasticsearch
