apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.5
        ports:
        - containerPort: 2379
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: ETCD_ENABLE_V2
          value: "true"
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd:2379"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        volumeMounts:
        - name: etcd-storage
          mountPath: /bitnami/etcd
      volumes:
      - name: etcd-storage
        persistentVolumeClaim:
          claimName: etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: shenma
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
