apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-web
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-web
  template:
    metadata:
      labels:
        app: portal-web
    spec:
      containers:
      - name: portal-web
        image: docker.io/nginx:1.27.1
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: portal-web-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: portal-web-pvc
          mountPath: /var/www
      volumes:
      - name: portal-web-config
        configMap:
          name: portal-web-config
      - name: portal-web-pvc
        persistentVolumeClaim:
          claimName: portal-web-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: portal-web
  namespace: shenma
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: portal-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-web-pvc
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-web-config
  namespace: shenma
data:
  nginx.conf: |
    worker_processes 1;
    error_log stderr notice;
    events {
        worker_connections 1024;
    }

    http {
        variables_hash_max_size 1024;
        access_log off;
        real_ip_header X-Real-IP;
        charset utf-8;
        include /etc/nginx/mime.types;
        default_type  application/octet-stream;

        server {
            listen 80;

            root /var/www;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }

            location /static/ {
                alias static/;
            }

            location /login/ {
                alias login/;
            }
            # 配置对 CSS、JS、PNG、SVG 文件的访问
            location ~* \.(css|js|png|svg)$ {
                expires 30d;  # 设置缓存过期时间
                add_header Access-Control-Allow-Origin *;  # 允许所有域访问
                add_header Access-Control-Allow-Methods 'GET, OPTIONS';  # 允许的请求方法
                add_header Access-Control-Allow-Headers 'Content-Type';  # 允许的请求头
            }

            # 其他文件类型的配置（可选）
            location ~* \.(jpg|jpeg|gif|ico|woff|woff2|ttf|eot)$ {
                expires 30d;  # 设置缓存过期时间
                add_header Access-Control-Allow-Origin *;  # 允许所有域访问
            }
        }
    }
