apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: shenma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: TZ
          value: "Asia/Shanghai"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shenma
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: shenma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
